version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '08:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - 'dependencies'
    groups:
      react-ecosystem:
        patterns:
          - 'react*'
          - '@types/react*'
      mui-ecosystem:
        patterns:
          - '@mui/*'
      testing-ecosystem:
        patterns:
          - 'jest*'
          - '@testing-library/*'
          - '@types/jest'
      build-tools:
        patterns:
          - 'vite*'
          - '@vitejs*'
          - 'typescript'